###
POST http://localhost:3000/user
Content-Type: application/json

{
        
    "username":"admin",
    "password":"123"


}
###
GET http://localhost:3000/
Content-Type: application/json
Authorization: Bearer token

{


}
###
POST http://localhost:3000/
Content-Type: application/json
Authorization: Bearer token

{
        
    "nome": "fulano de tal token",
    "telefone": "(00) 00000-0000",
    "email": "fulanodetal@gmail.com",
    "cep": "0000-000"

}
###
PUT http://localhost:3000/5
Content-Type: application/json
Authorization: Bearer token

{
        
    "nome": "fulano de tal pt token",
    "telefone": "(00) 00000-0000",
    "email": "fulanodetal@gmail.com",
    "cep": "0000-000"

}

###
DELETE  http://localhost:3000/3
Content-Type: application/json
Authorization: Bearer token

{


}